# Generated by Django 5.1.2 on 2026-02-16 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_artwork_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['name'], 'verbose_name_plural': 'Countries'},
        ),
    ]
