# Generated by Django 5.1.2 on 2026-03-19 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_artist_email_artist_phone_number_alter_country_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='iso_code',
            field=models.CharField(blank=True, help_text='2-character ISO country code (e.g. BR, MA)', max_length=2, null=True, unique=True),
        ),
    ]
