# Generated by Django 5.1.2 on 2026-03-19 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_country_iso_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='image',
        ),
        migrations.AddField(
            model_name='activity',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='activities/documents/'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='date',
            field=models.DateField(),
        ),
    ]
