# Generated by Django 5.1.2 on 2026-03-20 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_country_image_activity_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='countries/'),
        ),
        migrations.AddField(
            model_name='country',
            name='svg_path',
            field=models.TextField(blank=True, help_text='SVG path d attribute(s) — paste full path data', null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='svg_viewbox',
            field=models.CharField(blank=True, help_text='e.g. 525 460 20 15', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='iso_code',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
