# Generated by Django 5.1.2 on 2026-03-20 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_country_image_country_svg_path_country_svg_viewbox_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='svg_path',
        ),
        migrations.RemoveField(
            model_name='country',
            name='svg_viewbox',
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(help_text='Must match the category name in Artwork', max_length=100, unique=True),
        ),
    ]
